# SEO
title: Colin Garvey
email: colin.garvey@example.com
description: >- 
  "software engineering, systems architecture, coffee, and powerlifting"
baseurl: null 
url: https://colingarvey.github.io 
twitter_username: colingarvey
github_username:  colingarvey
github: [metadata]

# AUTHOR
author:
  name: "Colin Garvey"
  avatar: "/assets/images/colin_headshot.jpg"
  bio: "Professional software engineer, systems architect, and connoisseur of all things"
  location: "SF Bay Area"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:colin.garvey@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://colingarvey.github.io"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/colingarvey"
# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-include-cache


include: ["_pages"]
repository: "colingarvey/colingarvey.github.io"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      author_profile: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
# Social Profile
social:
  type: Person 
  name:
  links:
    - "https://instagram.com/colingarvey"
    - "https://www.linkedin.com/in/colin-garvey-61687066/"

remote_theme: "mmistakes/minimal-mistakes@4.22.0"
minimal_mistakes_skin:  # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

search: true
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
