source "https://rubygems.org"

gem 'webrick'

group :jekyll_plugins do
  gem "github-pages"
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-paginate"
  gem "jekyll-include-cache"
  gem "jekyll-algolia"
end
